//
//  Drapeau.swift
//  PaintCode
//
//  Created by Alexandre Jouandin on 2015/05/26.
//  Copyright (c) 2015 Jouand.in. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class Drapeau : NSObject {

    //// Cache

    private struct Cache {
        static var orange: UIColor = UIColor(red: 1.000, green: 0.474, blue: 0.000, alpha: 1.000)
        static var noir90: UIColor = UIColor(red: 0.167, green: 0.167, blue: 0.167, alpha: 1.000)
        static var blanc20: UIColor = UIColor(red: 0.813, green: 0.813, blue: 0.813, alpha: 1.000)
    }

    //// Colors

    public class var orange: UIColor { return Cache.orange }
    public class var noir90: UIColor { return Cache.noir90 }
    public class var blanc20: UIColor { return Cache.blanc20 }

    //// Drawing Methods

    public class func drawVentometre(#angle: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Ensemble
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 160, 160)
        CGContextRotateCTM(context, -angle * CGFloat(M_PI) / 180)



        //// Support
        //// cable Drawing
        var cablePath = UIBezierPath()
        cablePath.moveToPoint(CGPointMake(-22.75, -26.75))
        cablePath.addLineToPoint(CGPointMake(-5.72, 3.62))
        cablePath.lineCapStyle = kCGLineCapRound;

        Drapeau.blanc20.setFill()
        cablePath.fill()
        Drapeau.blanc20.setStroke()
        cablePath.lineWidth = 0.5
        cablePath.stroke()


        //// cable 2 Drawing
        var cable2Path = UIBezierPath()
        cable2Path.moveToPoint(CGPointMake(6.35, 3.62))
        cable2Path.addLineToPoint(CGPointMake(21.25, -26.04))
        cable2Path.lineCapStyle = kCGLineCapRound;

        Drapeau.blanc20.setFill()
        cable2Path.fill()
        Drapeau.blanc20.setStroke()
        cable2Path.lineWidth = 0.5
        cable2Path.stroke()


        //// Mat Drawing
        var matPath = UIBezierPath(ovalInRect: CGRectMake(-7.5, -7.5, 15, 15))
        Drapeau.blanc20.setFill()
        matPath.fill()




        //// volant
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clipper
        var clipperPath = UIBezierPath()
        clipperPath.moveToPoint(CGPointMake(-5.85, -153.5))
        clipperPath.addLineToPoint(CGPointMake(6.85, -153.5))
        clipperPath.addLineToPoint(CGPointMake(28, -26))
        clipperPath.addLineToPoint(CGPointMake(-27, -26))
        clipperPath.addLineToPoint(CGPointMake(-5.85, -153.5))
        clipperPath.closePath()
        clipperPath.addClip()


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRectMake(-27.5, -111.5, 56, 15))
        Drapeau.orange.setFill()
        rectanglePath.fill()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRectMake(-27.5, -96.5, 56, 14))
        Drapeau.blanc20.setFill()
        rectangle2Path.fill()


        //// Rectangle 3 Drawing
        let rectangle3Path = UIBezierPath(rect: CGRectMake(-27.5, -82.5, 56, 15))
        Drapeau.orange.setFill()
        rectangle3Path.fill()


        //// Rectangle 4 Drawing
        let rectangle4Path = UIBezierPath(rect: CGRectMake(-27.5, -67.5, 56, 14))
        Drapeau.blanc20.setFill()
        rectangle4Path.fill()


        //// Rectangle 5 Drawing
        let rectangle5Path = UIBezierPath(rect: CGRectMake(-27.5, -53.5, 56, 14))
        Drapeau.orange.setFill()
        rectangle5Path.fill()


        //// Rectangle 6 Drawing
        let rectangle6Path = UIBezierPath(rect: CGRectMake(-27.5, -39.5, 56, 14))
        Drapeau.blanc20.setFill()
        rectangle6Path.fill()


        //// Rectangle 7 Drawing
        let rectangle7Path = UIBezierPath(rect: CGRectMake(-27.5, -140.5, 56, 16))
        Drapeau.orange.setFill()
        rectangle7Path.fill()


        //// Rectangle 8 Drawing
        let rectangle8Path = UIBezierPath(rect: CGRectMake(-27.5, -124.5, 56, 13))
        Drapeau.blanc20.setFill()
        rectangle8Path.fill()


        //// Rectangle 9 Drawing
        let rectangle9Path = UIBezierPath(rect: CGRectMake(-27.5, -153.5, 56, 13))
        Drapeau.blanc20.setFill()
        rectangle9Path.fill()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)



        CGContextRestoreGState(context)
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
